Do not omit parens for 0-arity function definitions
uohzxela/ex_format pull request #21
Opened 2017-07-23 16:41 UTC by uohzxela

2017-07-23 19:11 UTC, whatyouhide requested changes

2017-07-23 19:11 UTC, whatyouhide commented on lib/ex_format.ex
> +          sym in [:def, :defp, :defmacro, :defmacrop] ->
defdelegate should be here as well

2017-07-23 22:57 UTC, uohzxela commented
@whatyouhide updated

2017-07-23 23:42 UTC, lpil commented on lib/ex_format.ex
>    # TODO: rename to update_meta
Seems this TODO can be removed

2017-07-23 23:49 UTC, lpil commented on test/unit/fun_parens_test.exs
> +      def f(), do: something
Huh, I'm surprised by the params on zero arity function definitions. Wasn't aware that was a common or recommended style

2017-07-24 07:17 UTC, whatyouhide commented on test/unit/fun_parens_test.exs
> +      def f(), do: something
@lpil for now ;)

The idea is: we call them with parens, we define them with parens when there are arguments, what sense does it make to define them without parens?

2017-07-24 07:18 UTC, whatyouhide approved these changes

2017-07-24 07:46 UTC, lpil commented on test/unit/fun_parens_test.exs
> +      def f(), do: something
Seems reasonable. :)

2017-07-24 11:12 UTC, merged