Remove agent state
uohzxela/ex_format pull request #71
Opened 2017-08-15 20:58 UTC by uohzxela

2017-08-15 21:18 UTC, whatyouhide requested changes

2017-08-15 21:18 UTC, whatyouhide commented on lib/ex_format/comments.ex
> +    end
The whole `if` can be replaced with

```elixir
Map.update(inline_comments, k, [v], &(&1 ++ [v]))
```

2017-08-15 21:18 UTC, whatyouhide commented on lib/ex_format/lines.ex
> +    |> Map.new
Can be replaced with

```elixir
lines = String.split(code_string, "\n")
for {line, index} <- Enum.with_index(lines, _offset = 1),
    into: %{},
    do: {index, String.trim(line)}
```

2017-08-16 00:54 UTC, uohzxela commented on lib/ex_format/comments.ex
> +    end
Elegant! That worked perfectly.

2017-08-16 00:56 UTC, uohzxela commented on lib/ex_format/lines.ex
> +    |> Map.new
Thank you, this looks way better.

2017-08-16 00:57 UTC, uohzxela commented
@whatyouhide updated and ready to merge :)

2017-08-16 16:41 UTC, whatyouhide approved these changes

2017-08-16 20:16 UTC, merged